export const blogsData = [
  {
    id: "1",
    image: "/best-food-image.jpg",
    author: "Sarah Johnson",
    comments: 35,
    date: "24th March 2024",
    title: "5-Minute Recipes for Busy Weekdays",
    des: "Discover the ultimate collection of quick and easy recipes that fit perfectly into your hectic schedule. Whether you’re rushing to work in the morning, juggling tasks throughout the day, or winding down after a long evening, these recipes are your go-to solution. Packed with flavor, nutrition, and convenience, these 5-minute meal ideas help you whip up satisfying breakfasts, lunches, dinners, and snacks without compromising on quality.",
    para1:
      "When food becomes a love language, it brings people closer together. Cooking is more than just making meals—it’s a heartfelt way to express care and affection. In many cultures, especially among Asian American and Pacific Islander (AAPI) communities, food serves as a bridge for love and connection. These quick recipes allow you to share love and warmth even when time is limited.",
    para2:
      "For individuals with packed schedules, finding time to prepare healthy meals can be a challenge. These recipes offer a solution. Perfect for busy professionals, parents, and students, these dishes are designed to be quick without sacrificing nutrition. Whether you need breakfast on the go or a simple dinner after work, these ideas will keep you energized.",
    para3:
      "The essence of these recipes lies in simplicity. With minimal prep time and straightforward instructions, cooking becomes a stress-free experience. Perfect for beginners and experts alike, these dishes celebrate the joy of effortless cooking",
    point1:
      "Cooking is love made visible: These 5-minute recipes let you create meals infused with love and care.",
    point2:
      "We’re an open book: Transparency in ingredients and process ensures easy replication at home.",
    point3:
      "100% goes to the field: Fresh, simple, and wholesome ingredients are the foundation of every recipe.",
    point4:
      "Received the highest grades: Loved and tested by home cooks, these recipes deliver on flavor and satisfaction.",
    para4:
      "In today’s fast-paced world, cooking is often sidelined due to time constraints. These recipes address that challenge by focusing on efficient preparation, easily accessible ingredients, and versatile flavors. Say goodbye to takeout and hello to homemade goodness.",
    img1: "/post-inner.jpg",
    para5:
      "Cooking doesn’t have to be time-consuming or complicated. With these 5-minute recipes, you can nourish yourself and your loved ones with meals made from the heart. Share these ideas with friends, experiment with new flavors, and transform the way you think about fast and fresh cooking.",
    para6:
      "I watch cooking change the cook, just as it transforms the food.Cooking is a journey, and these recipes are here to make it joyful, quick, and fulfilling.",
  },
  {
    id: "2",
    image: "/blog2.jpg",
    author: "Micheal Green",
    comments: 42,
    date: "7th August 2024",
    title: "How to Pair Food with Drinks",
    des: "Enhance your dining experience by learning the art of pairing food with the perfect drink. Whether you’re planning a casual dinner, a festive celebration, or a gourmet meal, this guide will help you find the best combinations that elevate flavors and bring harmony to your table. Discover tips, tricks, and pairing secrets for wine, cocktails, non-alcoholic drinks, and more!",
    para1:
      "Pairing food with drinks is more than just a culinary trend—it's a way to create memorable dining experiences. The right pairing brings out the best flavors in both the food and the drink, creating a perfect balance. From classic wine and cheese pairings to creative combinations with cocktails and mocktails, this guide will show you how to elevate every meal with thoughtful pairings.",
    para2:
      "Understanding flavor profiles is the first step in successful pairing. Whether it’s the sweetness of a dessert or the richness of a steak, choosing a drink that complements or contrasts these flavors can create a delightful balance.",
    para3:
      "Wine and Cheese: A timeless combination with endless possibilities—pair creamy cheeses with white wines and aged cheeses with bold reds.Pizza and Beer: The carbonation in beer complements the richness of cheesy, saucy pizzas. Seafood and White Wine: Light, citrusy wines enhance the delicate flavors of seafood.",
    point1:
      "Balance is key: Find harmony between the flavors of food and drink.",
    point2:
      "Opposites attract: Pair sweet and savory or acidic and creamy for a perfect match.",
    point3:
      "Consider the weight: Light dishes pair best with lighter drinks, while hearty meals need bold beverages.",
    point4:
      "Experiment and enjoy: Don’t be afraid to mix and match until you find your favorite pairings!",
    para4:
      "For those who prefer non-alcoholic drinks, pairing options are just as exciting. Sparkling water with fresh fruit is perfect for salads, while herbal teas enhance the flavors of light desserts. Lemonade pairs wonderfully with grilled dishes for a refreshing twist.",
    img1: "/post-inner.jpg",
    para5:
      "Pairing food with drinks is an art that anyone can master. Whether you’re dining solo, hosting friends, or planning a special event, the right pairing can elevate the flavors of your meal and make every bite more enjoyable. Use this guide as a starting point to explore new combinations and create unforgettable dining experiences.",
    para6:
      "Good food and good drinks make great memories.The perfect pairing brings people together, so experiment, savor, and enjoy the journey of flavor discovery.",
  },
  {
    id: "3",
    image: "/blog3.jpg",
    author: "Dr. Emily Carter",
    comments: 35,
    date: "17th October 2024",
    title: "Health Benefits of Spices You Use Daily ",
    des: "Discover how everyday spices like turmeric, cinnamon, and garlic can transform your health. Learn about their powerful benefits and how to incorporate them into your meals.",
    para1:
      "Spices are more than just a way to enhance flavor—they are packed with nutrients and compounds that can significantly boost your overall well-being. For centuries, spices have been used not only in cooking but also in traditional medicine to prevent and treat various ailments.",
    para2:
      "Turmeric, one of the most popular spices, is rich in curcumin, which has strong anti-inflammatory and antioxidant properties. It helps in reducing joint pain, improving skin health, and even enhancing brain function. Similarly, cinnamon is well-known for its ability to regulate blood sugar levels and improve heart health.",
    para3:
      "Garlic stands out as a superfood spice due to its ability to lower cholesterol and blood pressure. It also strengthens the immune system. On the other hand, ginger is a natural remedy for nausea, digestion issues, and inflammation, making it a must-have in your daily meals.",
    point1:
      "Garlic stands out as a superfood spice due to its ability to lower cholesterol and blood pressure. It also strengthens the immune system. On the other hand, ginger is a natural remedy for nausea, digestion issues, and inflammation, making it a must-have in your daily meals.",
    point2: "Cinnamon helps in blood sugar regulation and heart health.",
    point3: "Garlic strengthens immunity and promotes heart health.",
    point4: "Ginger aids digestion and reduces nausea naturally.",
    para4:
      "Adding these spices to your daily diet doesn’t have to be complicated. You can sprinkle cinnamon on your coffee, include turmeric in your soups or stews, and use garlic and ginger in your stir-fries or teas. These small changes can have a big impact on your health over time",
    img1: "/post-inner.jpg",
    para5:
      "Spices like black pepper and cardamom are also great additions to your meals. Black pepper enhances nutrient absorption, while cardamom is known for its detoxifying properties and ability to improve digestion. Together, they can make your dishes healthier and more flavorful.",
    para6:
      "By using spices consciously in your cooking, you’re not just adding flavor but also making a commitment to a healthier lifestyle. These everyday ingredients have powerful effects on your body, proving that good health starts in the kitchen.",
  },
  {
    id: "4",
    image: "/blog4.jpg",
    author: "Rachel Adams",
    comments: 24,
    date: "15th January 2024",
    title: "Why Organic Ingredients Matter",
    des: "Explore the importance of organic ingredients for your health, the environment, and sustainable living. Discover why choosing organic is a step toward a healthier and greener future.",
    para1:
      "Organic ingredients are more than just a trend—they are a commitment to better health, environmental sustainability, and ethical farming practices. Unlike conventional produce, organic ingredients are grown without synthetic fertilizers, pesticides, or genetically modified organisms (GMOs), making them a safer and healthier option for you and your family.",
    para2:
      "Consuming organic products reduces your exposure to harmful chemicals and toxins that are often present in non-organic food. Studies have shown that organic fruits and vegetables contain higher levels of antioxidants, which are essential for fighting free radicals and preventing chronic diseases.",
    para3:
      "Organic farming practices prioritize the health of the soil, water, and ecosystems. By avoiding harmful chemicals, organic farms help preserve biodiversity, protect pollinators, and reduce soil erosion, making them better for the planet. Additionally, organic livestock are raised without antibiotics or growth hormones, ensuring humane treatment and healthier meat or dairy products",
    point1: "Organic foods are free from synthetic pesticides and fertilizers",
    point2: "Higher levels of antioxidants in organic produce improve health.",
    point3:
      "Organic farming promotes biodiversity and environmental sustainability",
    point4:
      "Ethical treatment of animals in organic farming ensures quality products.",
    para4:
      "By choosing organic ingredients, you are supporting small-scale farmers and promoting a more sustainable food system. Organic farming practices often rely on crop rotation, composting, and natural pest control methods, which result in better soil health and more nutrient-dense produce.",
    img1: "/post-inner.jpg",
    para5:
      "The benefits of organic ingredients extend beyond personal health. They contribute to reducing greenhouse gas emissions and water pollution caused by conventional farming methods. Choosing organic is a step toward combating climate change and preserving the planet for future generations.",
    para6:
      "Switching to organic ingredients doesn’t have to be overwhelming. Start small by incorporating organic fruits, vegetables, and grains into your diet. Every organic choice you make is a step toward a healthier lifestyle and a healthier planet, proving that what’s good for nature is also good for you",
  },
  {
    id: "5",
    image: "/blog5.jpg",
    author: "Daniel Lewis",
    comments: 40,
    date: "14th December 2024",
    title: "The Ultimate Guide to Coffee Lovers",
    des: "Discover the art of coffee-making, explore brewing techniques, and learn about the world's finest coffee beans. This guide is a must-read for all coffee enthusiasts!",
    para1:
      "Coffee is more than just a morning beverage—it's a culture, a lifestyle, and a passion for millions around the world. Whether you’re a casual drinker or a dedicated connoisseur, this ultimate guide will help you deepen your appreciation for coffee. From bean origins to brewing methods, there's a world of flavor waiting to be explored.",
    para2:
      "Understanding your coffee starts with the bean. Coffee comes from two main species: Arabica and Robusta. Arabica beans are known for their smooth and complex flavors, while Robusta beans have a stronger, more bitter taste. Learning to identify the differences between these beans can enhance your coffee experience.",
    para3:
      "The brewing method plays a crucial role in determining the flavor and aroma of your coffee. Popular techniques include pour-over, French press, espresso, and cold brew. Each method brings out unique characteristics of the beans, allowing you to tailor your coffee to your preferences. Experiment with grind sizes, water temperature, and brewing time to perfect your cup",
    point1: "Discover the world's best coffee-growing regions.",
    point2: "Learn how to grind your coffee for the perfect brew",
    point3: "Explore brewing methods like pour-over and cold brew",
    point4: "Understand the difference between Arabica and Robusta beans.",
    para4:
      "For the true coffee lover, the journey doesn’t end with brewing. Pairing coffee with the right foods can elevate your experience. For instance, a dark roast pairs beautifully with chocolate desserts, while a light roast complements citrusy or fruity pastries. Exploring these combinations can turn your coffee break into a gourmet adventure.",
    img1: "/post-inner.jpg",
    para5:
      "The health benefits of coffee are an added bonus. Rich in antioxidants, coffee can boost energy levels, improve focus, and even lower the risk of certain diseases. However, moderation is key—overconsumption can lead to negative effects like insomnia or increased heart rate.",
    para6:
      "Being a coffee lover is not just about drinking coffee—it's about celebrating its rich history, diverse flavors, and cultural significance. Whether you’re exploring a local café, trying new beans, or perfecting your home brew, every sip is a journey. Embrace the adventure, and let your love for coffee grow stronger with every cup",
  },
];
export const menuData = [
  {
    id: "1",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Crispy, golden, and perfectly seasoned, our Classic French Fries are a crowd-pleaser.",
    price: 120,
    discount: "150",
    stock: "In Stock",
    reviews: 35,
    des1: "Our Classic French Fries are made from the finest potatoes, hand-cut, and fried to golden perfection. Each bite delivers a crispy exterior and a fluffy interior that pairs perfectly with your favorite dips and sauces.",
    des2: "These fries are lightly salted and seasoned to bring out their natural flavors, making them a great snack or side for any meal. Perfect for parties, gatherings, or just indulging in a classic comfort food, they’re sure to satisfy every craving.",
    benefits1: "Prepared with fresh, high-quality potatoes.",
    benefits2: "Crispy texture and golden color for an irresistible taste.",
    benefits3: "Lightly seasoned to enhance the natural flavor.",
    benefits4: "Perfect as a snack or a side dish for meals.",
    benefits5: "Pairs well with a variety of dips and sauces.",
  },
  {
    id: "2",
    category: "fries",
    name: "Cheese Fries",
    image: "/fries2.jpg",
    des: "Loaded with melted cheese, our cheese Fries are the ultimate indulgence for every cheese lover.",
    price: 15,
    discount: "$20",
    stock: "Out Stock",
    reviews: 22,
    des1: "Our Cheese Fries are a delicious upgrade to the classic fries, smothered in a generous layer of rich, gooey melted cheese. Each bite delivers a perfect combination of crispy fries and creamy cheese that will leave you craving more",
    des2: "Perfect for sharing or enjoying as a treat for yourself, these fries are a great addition to any meal or as a standalone snack. Topped with your choice of extra seasonings or sauces, they are a cheesy delight everyone will love.",
    benefits1: "Made with freshly cooked crispy fries",
    benefits2: "Topped with rich, creamy, melted cheese.",
    benefits3: "Perfect as a snack or party appetizer.",
    benefits4: "Pairs well with extra toppings like jalapeños or herbs.",
    benefits5: "A must-try for cheese lovers",
  },
  {
    id: "3",
    category: "fries",
    name: "Curly Fries",
    image: "/fries3.jpg",
    des: "Fun, spiral-shaped fries with a crispy texture and bold flavor.",
    price: 25,
    stock: "In Stock",
    reviews: 22,
    des1: "Curly Fries bring a playful twist to your fry experience, combining a crispy texture with an irresistible bold flavor. Perfectly seasoned, these fries are a fun and delicious treat.",
    des2: "Serve them with your favorite dipping sauce or enjoy them as a snack. Curly Fries add flair to any meal and are always a crowd-pleaser.",
    benefits1: "Unique spiral shape for fun and flavor.",
    benefits2: "Crispy texture and bold seasoning.",
    benefits3: "Perfect as a side dish or snack.",
    benefits4: "Pairs well with various dips and sauces.",
    benefits5: "Loved by both kids and adults.",
  },
  {
    id: "4",
    category: "fries",
    name: "Loaded Fries",
    image: "/fries4.jpg",
    des: "Smothered in cheese, bacon, and a drizzle of ranch dressing.",
    price: 27,
    discount: "$35",
    stock: "Out Stock",
    reviews: 22,
    des1: "Loaded Fries take your fry game to the next level. Topped with melted cheese, crispy bacon, and a drizzle of ranch, they are a decadent indulgence.",
    des2: "Whether for sharing or enjoying alone, Loaded Fries are a perfect mix of savory flavors and rich textures that satisfy any craving.",
    benefits1: "Topped with creamy cheese and crispy bacon.",
    benefits2: "Drizzled with ranch dressing for extra flavor.",
    benefits3: "Perfect for parties or a special treat.",
    benefits4: "Customizable with additional toppings.",
    benefits5: "Irresistibly rich and flavorful.",
  },
  {
    id: "5",
    category: "fries",
    name: "Sweet Potato Fries",
    image: "/fries5.jpg",
    des: "Lightly salted and perfectly crispy, with a hint of natural sweetness.",
    price: 23,
    stock: "In Stock",
    reviews: 22,
    des1: "Sweet Potato Fries offer a healthier twist with a natural sweetness that complements their crispy texture. Lightly salted, they are a flavorful and nutritious option.",
    des2: "Great as a side or snack, these fries pair well with a variety of dips or enjoy them on their own. Sweet Potato Fries add variety to your fry collection.",
    benefits1: "Made with fresh sweet potatoes.",
    benefits2: "Perfectly crispy with natural sweetness.",
    benefits3: "A healthier alternative to regular fries.",
    benefits4: "Pairs well with savory or sweet dips.",
    benefits5: "Loved by health-conscious foodies.",
  },
  {
    id: "6",
    category: "fries",
    name: "Spicy Fries",
    image: "/fries6.jpg",
    des: "Seasoned with a zesty spice blend for those who like a little heat.",
    price: 36,
    discount: "$40",
    stock: "Out Stock",
    reviews: 22,
    des1: "Spicy Fries are perfect for heat seekers. With a bold, zesty spice blend, these fries deliver the perfect kick of flavor.",
    des2: "Serve them alongside a cooling dip or enjoy them as-is. Spicy Fries are an exciting addition to any meal or snack time.",
    benefits1: "Boldly seasoned with a zesty spice blend.",
    benefits2: "Crispy texture with a fiery kick.",
    benefits3: "Great for heat lovers and spice enthusiasts.",
    benefits4: "Pairs well with cooling dips or sauces.",
    benefits5: "A thrilling flavor experience.",
  },
  {
    id: "7",
    category: "burgers",
    name: "Beef Burger",
    image: "/burger1.png",
    des: "Juicy beef patty grilled to perfection, topped with fresh lettuce, tomato, and cheese.",
    price: 55,
    discount: "$60",
    stock: "In Stock",
    reviews: 45,
    des1: "Beef Burger is a classic favorite, featuring a tender beef patty grilled to perfection and topped with fresh ingredients.",
    des2: "Perfect for lunch, dinner, or any time you're craving a hearty burger.",
    benefits1: "Grilled beef patty packed with flavor.",
    benefits2: "Fresh toppings add crunch and taste.",
    benefits3: "A satisfying meal for any occasion.",
    benefits4: "Pairs well with fries or a cold beverage.",
    benefits5: "Loved by burger enthusiasts worldwide.",
  },
  {
    id: "8",
    category: "burgers",
    name: "Cheese Burger",
    image: "/burger2.png",
    des: "Melted cheese on a juicy beef patty, served with fresh veggies and a soft bun.",
    price: 60,
    discount: "$65",
    stock: "In Stock",
    reviews: 50,
    des1: "Cheese Burger combines the classic beef patty with rich, melted cheese for a satisfying flavor explosion.",
    des2: "A timeless favorite for cheese lovers.",
    benefits1: "Rich, melted cheese adds indulgence.",
    benefits2: "Perfectly grilled beef patty.",
    benefits3: "Fresh veggies for balance.",
    benefits4: "Soft bun enhances the experience.",
    benefits5: "An all-time favorite comfort food.",
  },
  {
    id: "9",
    category: "burgers",
    name: "Chicken Burger",
    image: "/burger3.png",
    des: "Crispy or grilled chicken fillet topped with fresh lettuce, mayo, and a soft bun.",
    price: 50,
    discount: "$55",
    stock: "In Stock",
    reviews: 35,
    des1: "Chicken Burger features tender, flavorful chicken fillet with fresh toppings for a wholesome meal.",
    des2: "Great for chicken lovers seeking a lighter option.",
    benefits1: "Crispy or grilled chicken fillet.",
    benefits2: "Fresh and flavorful toppings.",
    benefits3: "Healthier choice for burger lovers.",
    benefits4: "Soft bun complements the textures.",
    benefits5: "Perfect for lunch or dinner.",
  },
  {
    id: "10",
    category: "burgers",
    name: "Veggie Burger",
    image: "/burger4.png",
    des: "Packed with a hearty vegetable patty, fresh veggies, and a flavorful sauce.",
    price: 45,
    discount: "$50",
    stock: "In Stock",
    reviews: 30,
    des1: "Veggie Burger is a delicious choice for vegetarians, packed with wholesome ingredients.",
    des2: "Enjoy a flavorful and satisfying plant-based meal.",
    benefits1: "Hearty vegetable patty.",
    benefits2: "Wholesome, fresh ingredients.",
    benefits3: "Great for vegetarians and health-conscious eaters.",
    benefits4: "Flavorful sauce adds depth.",
    benefits5: "Perfect as a light, nutritious meal.",
  },
  {
    id: "11",
    category: "burgers",
    name: "Double Patty Burger",
    image: "/burger5.png",
    des: "Two juicy beef patties stacked high, with double the cheese and toppings.",
    price: 70,
    discount: "$80",
    stock: "In Stock",
    reviews: 60,
    des1: "Double Patty Burger is the ultimate indulgence for true burger fans with its generous portions.",
    des2: "Perfect for those with a big appetite or looking to share.",
    benefits1: "Double the beefy goodness.",
    benefits2: "Generous portion of cheese and toppings.",
    benefits3: "A hearty and satisfying meal.",
    benefits4: "Great for sharing with a friend.",
    benefits5: "Pairs perfectly with a side of fries.",
  },
  {
    id: "12",
    category: "burgers",
    name: "Black Beef Burger",
    image: "/burger6.png",
    des: "Unique black bun with a juicy beef patty, fresh toppings, and bold flavors.",
    price: 65,
    discount: "$70",
    stock: "In Stock",
    reviews: 40,
    des1: "Black Beef Burger offers a visually striking twist on the classic burger with a unique black bun.",
    des2: "Perfect for adventurous eaters and food enthusiasts.",
    benefits1: "Eye-catching black bun.",
    benefits2: "Juicy and flavorful beef patty.",
    benefits3: "Fresh toppings for balance.",
    benefits4: "Bold and exciting flavor profile.",
    benefits5: "A standout choice for burger lovers.",
  }, 
  {
    id: "13",
    category: "beverages",
    name: "Coke",
    image: "/beverage1.jpg",
    price: 30,
    discount: "$40",
    des: "",
    stock: "In Stock",
    reviews: 22,
    des1: "Coke is a classic carbonated beverage with a unique and refreshing flavor loved by millions worldwide.",
    des2: "Perfect for any occasion, Coke pairs well with meals or can be enjoyed on its own as a thirst-quenching treat.",
    benefits1: "Classic and refreshing taste.",
    benefits2: "Pairs well with a variety of meals.",
    benefits3: "Loved by people of all ages.",
    benefits4: "Perfect for parties, picnics, or daily enjoyment.",
    benefits5: "A timeless beverage that never goes out of style.",
  },  
  {
    id: "14",
    category: "beverages",
    name: "Sprite",
    image: "/beverage2.jpg",
    price: 30,
    discount: "$40",
    des: "",
    stock: "In Stock",
    reviews: 18,
    des1: "Sprite is a refreshing lemon-lime flavored beverage that quenches your thirst and revitalizes you.",
    des2: "Perfect for any occasion, Sprite offers a crisp, clean taste that pairs well with any meal or as a standalone refreshment.",
    benefits1: "Light and refreshing lemon-lime flavor.",
    benefits2: "Crisp and clean taste.",
    benefits3: "Perfect for all occasions.",
    benefits4: "Pairs well with meals or as a standalone drink.",
    benefits5: "A classic favorite for soda lovers.",
  },
  {
    id: "15",
    category: "beverages",
    name: "Iced Tea",
    image: "/beverage3.jpg",
    price: 35,
    discount: "$45",
    des: "",
    stock: "In Stock",
    reviews: 25,
    des1: "Iced Tea is a chilled and flavorful beverage, brewed to perfection and served with a touch of sweetness.",
    des2: "Ideal for a warm day, this classic drink provides a refreshing and soothing experience.",
    benefits1: "Brewed tea served chilled.",
    benefits2: "Lightly sweetened for a balanced taste.",
    benefits3: "Perfect for summer or warm weather.",
    benefits4: "Refreshing and soothing.",
    benefits5: "A classic beverage for tea lovers.",
  },
  {
    id: "16",
    category: "beverages",
    name: "Fresh Lemonade",
    image: "/beverage4.jpg",
    price: 40,
    discount: "$50",
    des: "",
    stock: "In Stock",
    reviews: 30,
    des1: "Fresh Lemonade is a tangy and sweet beverage made from freshly squeezed lemons, sugar, and chilled water.",
    des2: "Perfect for a hot day or to complement your meal, Fresh Lemonade is both refreshing and invigorating.",
    benefits1: "Made with freshly squeezed lemons.",
    benefits2: "Balanced tangy and sweet flavor.",
    benefits3: "Refreshing and invigorating.",
    benefits4: "Great for hot days or as a meal complement.",
    benefits5: "A timeless favorite for all ages.",
  },
  {
    id: "17",
    category: "beverages",
    name: "Classic Milkshake",
    image: "/beverage5.jpg",
    price: 50,
    discount: "$60",
    des: "",
    stock: "In Stock",
    reviews: 40,
    des1: "Classic Milkshake is a creamy and indulgent treat, made with milk, ice cream, and your choice of flavor.",
    des2: "Perfect as a dessert or a sweet beverage, it’s a nostalgic delight for all ages.",
    benefits1: "Rich and creamy texture.",
    benefits2: "Available in various classic flavors.",
    benefits3: "Perfect as a dessert or treat.",
    benefits4: "Loved by kids and adults alike.",
    benefits5: "A nostalgic and indulgent drink.",
  },
  {
    id: "18",
    category: "beverages",
    name: "Iced Coffee",
    image: "/beverage6.jpg",
    price: 45,
    discount: "$55",
    des: "",
    stock: "In Stock",
    reviews: 35,
    des1: "Iced Coffee is a smooth and refreshing coffee beverage, served chilled and lightly sweetened.",
    des2: "Great for coffee lovers seeking a cold and energizing drink.",
    benefits1: "Smooth and chilled coffee.",
    benefits2: "Lightly sweetened for a balanced taste.",
    benefits3: "Perfect for hot days or as an energy boost.",
    benefits4: "Pairs well with pastries or snacks.",
    benefits5: "A favorite for coffee enthusiasts.",
  },  
  {
    id: "19",
    category: "desiFood",
    name: "Chicken Biryani",
    image: "/desifood1.jpg",
    price: 30,
    discount: "$40",
    des: "",
    stock: "In Stock",
    reviews: 22,
    des1: "Chicken Biryani is a flavorful and aromatic rice dish cooked with tender chicken, spices, and herbs, offering a perfect blend of taste and tradition.",
    des2: "Ideal for lunch or dinner, Chicken Biryani pairs wonderfully with yogurt or salad and is a must-have for special occasions or everyday meals.",
    benefits1: "Rich in spices and flavors.",
    benefits2: "Made with tender chicken and aromatic basmati rice.",
    benefits3: "Perfect for family meals and gatherings.",
    benefits4: "Pairs well with yogurt or salad.",
    benefits5: "A classic and beloved dish in South Asian cuisine.",
  },
  {
    id: "20",
    category: "desiFood",
    name: "Mutton Karahi",
    image: "/desifood2.jpg",
    price: 50,
    discount: "$60",
    des: "",
    stock: "In Stock",
    reviews: 18,
    des1: "Mutton Karahi is a spicy and savory dish cooked in a traditional wok with mutton, tomatoes, and a unique blend of spices.",
    des2: "Best enjoyed with naan or paratha, Mutton Karahi is a hearty dish perfect for dinners and festive occasions.",
    benefits1: "Cooked in a traditional karahi for authentic flavor.",
    benefits2: "Rich in spices with tender mutton pieces.",
    benefits3: "Pairs perfectly with naan or paratha.",
    benefits4: "Ideal for special occasions and family dinners.",
    benefits5: "A signature dish of South Asian cuisine.",
  },
  {
    id: "21",
    category: "desiFood",
    name: "Beef Nihari",
    image: "/desifood.jpg",
    price: 45,
    discount: "$55",
    des: "",
    stock: "In Stock",
    reviews: 30,
    des1: "Beef Nihari is a slow-cooked stew made with tender beef shank, aromatic spices, and a rich, flavorful gravy.",
    des2: "Served with naan or roti, it is a traditional breakfast or dinner delicacy in South Asia.",
    benefits1: "Rich, slow-cooked beef stew.",
    benefits2: "Bursting with spices and flavors.",
    benefits3: "Best enjoyed with naan or roti.",
    benefits4: "Perfect for traditional meals.",
    benefits5: "A classic comfort food of South Asian cuisine.",
  },
  {
    id: "22",
    category: "desiFood",
    name: "Peshawari Chapli Kabab",
    image: "/desifood3.jpg",
    price: 40,
    discount: "$50",
    des: "",
    stock: "In Stock",
    reviews: 35,
    des1: "Peshawari Chapli Kabab is a flavorful minced meat patty infused with traditional spices and cooked to perfection.",
    des2: "Served with naan or as a side dish, it’s a popular and delightful treat for meat lovers.",
    benefits1: "Juicy and flavorful minced meat patty.",
    benefits2: "Infused with a blend of traditional spices.",
    benefits3: "Perfect as a main dish or appetizer.",
    benefits4: "Pairs well with naan, chutney, or salad.",
    benefits5: "A signature dish from Peshawar cuisine.",
  },
  {
    id: "23",
    category: "desiFood",
    name: "Chicken Handi",
    image: "/desifood4.jpg",
    price: 35,
    discount: "$45",
    des: "",
    stock: "In Stock",
    reviews: 28,
    des1: "Chicken Handi is a creamy and flavorful curry dish cooked with tender chicken, yogurt, and rich spices in a clay pot.",
    des2: "Best enjoyed with naan or roti, it’s a hearty meal for any occasion.",
    benefits1: "Cooked with a creamy and rich curry base.",
    benefits2: "Served in a traditional handi for authentic flavor.",
    benefits3: "Made with tender chicken and spices.",
    benefits4: "Perfect for family meals or special occasions.",
    benefits5: "A favorite among South Asian cuisine lovers.",
  },
  {
    id: "24",
    category: "desiFood",
    name: "Tandoori Roti",
    image: "/desifood5.jpg",
    price: 10,
    discount: "$15",
    des: "",
    stock: "In Stock",
    reviews: 40,
    des1: "Tandoori Roti is a soft and fluffy flatbread baked in a traditional clay oven for an authentic flavor.",
    des2: "Perfect for pairing with any curry or side dish, it’s a staple in South Asian meals.",
    benefits1: "Soft and fluffy flatbread.",
    benefits2: "Baked in a traditional tandoor oven.",
    benefits3: "Pairs well with all types of curries and sides.",
    benefits4: "A staple in South Asian cuisine.",
    benefits5: "Perfect for everyday meals or festive occasions.",
  },
  {
    id: "25",
    category: "desserts",
    name: "Gulab Jamun",
    image: "/dessert1.jpg",
    price: 30,
    discount: "$40",
    des: "",
    stock: "In Stock",
    reviews: 22,
    des1: "Gulab Jamun is a soft, melt-in-your-mouth dessert made with milk solids, deep-fried, and soaked in aromatic sugar syrup.",
    des2: "Perfect for festive occasions or as a delightful end to your meal, Gulab Jamun is a classic favorite in South Asian cuisine.",
    benefits1: "Rich in sweetness and flavor.",
    benefits2: "Loved by all age groups.",
    benefits3: "A classic dessert for celebrations.",
    benefits4: "Easy to pair with other desserts.",
    benefits5: "Perfect for satisfying your sweet cravings.",
  },
  {
    id: "26",
    category: "desserts",
    name: "Donuts",
    image: "/dessert2.jpg",
    price: 20,
    discount: "$25",
    des: "",
    stock: "In Stock",
    reviews: 18,
    des1: "Donuts are soft, fluffy treats with a variety of glazes and toppings, making them a versatile and popular dessert choice.",
    des2: "Perfect as a snack or dessert, donuts are available in a variety of flavors to suit every palate.",
    benefits1: "Wide variety of flavors and toppings.",
    benefits2: "Light, fluffy, and satisfying.",
    benefits3: "Perfect for sharing with friends and family.",
    benefits4: "Great for breakfast or dessert.",
    benefits5: "A universally loved sweet treat.",
  },
  {
    id: "27",
    category: "desserts",
    name: "Chocolate Lava Cake",
    image: "/dessert3.jpg",
    price: 50,
    discount: "$60",
    des: "",
    stock: "In Stock",
    reviews: 25,
    des1: "Chocolate Lava Cake is a rich, molten chocolate dessert with a gooey center, perfect for indulgent chocolate lovers.",
    des2: "Best served warm with a scoop of vanilla ice cream or fresh berries for an exquisite dessert experience.",
    benefits1: "Decadent chocolate flavor.",
    benefits2: "Molten center for added indulgence.",
    benefits3: "Pairs perfectly with ice cream or berries.",
    benefits4: "A luxurious dessert experience.",
    benefits5: "Loved by chocolate enthusiasts.",
  },
  {
    id: "28",
    category: "desserts",
    name: "Mango Cheesecake",
    image: "/dessert4.jpg",
    price: 45,
    discount: "$55",
    des: "",
    stock: "In Stock",
    reviews: 30,
    des1: "Mango Cheesecake combines the creamy richness of cheesecake with the tropical sweetness of mangoes.",
    des2: "Perfect for summer desserts or as a light, fruity end to any meal.",
    benefits1: "Rich and creamy texture.",
    benefits2: "Infused with the tropical flavor of mangoes.",
    benefits3: "Perfect for warm-weather celebrations.",
    benefits4: "A refreshing and light dessert option.",
    benefits5: "Loved by fruit and cheesecake enthusiasts.",
  },
  {
    id: "29",
    category: "desserts",
    name: "Ice Cream Sundae",
    image: "/dessert5.jpg",
    price: 35,
    discount: "$45",
    des: "",
    stock: "In Stock",
    reviews: 28,
    des1: "Ice Cream Sundae is a delightful dessert topped with sauces, sprinkles, nuts, and whipped cream for a customizable treat.",
    des2: "Ideal for all occasions, this dessert is a hit with both kids and adults alike.",
    benefits1: "Customizable with various toppings.",
    benefits2: "Loved by all age groups.",
    benefits3: "Perfect for hot summer days.",
    benefits4: "A fun and interactive dessert.",
    benefits5: "Combines creamy texture with exciting flavors.",
  },
  {
    id: "30",
    category: "desserts",
    name: "Brownie with Ice Cream",
    image: "/dessert6.jpg",
    price: 40,
    discount: "$50",
    des: "",
    stock: "In Stock",
    reviews: 35,
    des1: "Brownie with Ice Cream is a heavenly combination of a warm, gooey brownie topped with cold, creamy ice cream.",
    des2: "Perfect for those who love the mix of hot and cold textures in one decadent dessert.",
    benefits1: "Combination of warm and cold textures.",
    benefits2: "Rich chocolate flavor with creamy ice cream.",
    benefits3: "Perfect for sharing or indulging alone.",
    benefits4: "A favorite for celebrations and casual treats.",
    benefits5: "Complements other desserts well.",
  },
  {
    id: "31",
    category: "deals",
    name: "Burger Combo Deal",
    image: "/deal1.jpg",
    price: 30,
    discount: "$40",
    des: "",
    stock: "In Stock",
    reviews: 22,
    des1: "The Burger Combo Deal offers a delicious combination of a juicy burger, crispy fries, and a refreshing drink, all in one package.",
    des2: "Perfect for a quick and satisfying meal, this deal is a great option for burger lovers looking for a complete meal.",
    benefits1: "Includes a juicy burger, crispy fries, and a drink.",
    benefits2: "Great value for a full meal.",
    benefits3: "Perfect for a quick lunch or dinner.",
    benefits4: "Satisfies both hunger and taste cravings.",
    benefits5: "Ideal for burger enthusiasts.",
  },
  {
    id: "32",
    category: "deals",
    name: "Family Feast Deal",
    image: "/deal2.jpg",
    price: 50,
    discount: "$65",
    des: "",
    stock: "In Stock",
    reviews: 30,
    des1: "The Family Feast Deal is perfect for sharing with loved ones, featuring a variety of delicious items to satisfy everyone.",
    des2: "An ideal choice for gatherings, this deal offers a combination of dishes that are both filling and flavorful.",
    benefits1: "Great value for families or groups.",
    benefits2: "Includes a variety of menu items.",
    benefits3: "Perfect for celebrations or casual meals.",
    benefits4: "Saves time on meal preparation.",
    benefits5: "Loved by all age groups.",
  },
  {
    id: "33",
    category: "deals",
    name: "BBQ Platter Deal",
    image: "/deal3.jpg",
    price: 60,
    discount: "$75",
    des: "",
    stock: "In Stock",
    reviews: 35,
    des1: "The BBQ Platter Deal offers a mouthwatering assortment of grilled favorites, perfect for BBQ enthusiasts.",
    des2: "Enjoy a delicious combination of tender meats, flavorful sauces, and traditional sides in one meal.",
    benefits1: "Includes a variety of BBQ options.",
    benefits2: "Perfect for meat lovers.",
    benefits3: "Ideal for sharing with family or friends.",
    benefits4: "Combines great taste with value.",
    benefits5: "A satisfying meal for any occasion.",
  },
  {
    id: "34",
    category: "deals",
    name: "Dessert Lover's Deal",
    image: "/deal4.jpg",
    price: 40,
    discount: "$50",
    des: "",
    stock: "In Stock",
    reviews: 20,
    des1: "The Dessert Lover's Deal features a selection of sweet treats, ideal for satisfying your sweet tooth.",
    des2: "From cakes to ice creams, this deal is a dream come true for dessert enthusiasts.",
    benefits1: "A variety of desserts in one deal.",
    benefits2: "Perfect for celebrations or indulgent moments.",
    benefits3: "Great for sharing with friends and family.",
    benefits4: "High-quality ingredients and rich flavors.",
    benefits5: "An irresistible option for dessert lovers.",
  },
  {
    id: "35",
    category: "deals",
    name: "Lunch Box Deal",
    image: "/deal5.jpg",
    price: 25,
    discount: "$35",
    des: "",
    stock: "In Stock",
    reviews: 28,
    des1: "The Lunch Box Deal offers a balanced and delicious meal, ideal for quick and convenient lunches.",
    des2: "Perfect for office breaks or on-the-go meals, this deal provides taste and convenience in one package.",
    benefits1: "Quick and convenient meal option.",
    benefits2: "Includes a balanced selection of items.",
    benefits3: "Perfect for office or school lunches.",
    benefits4: "Great value for a complete meal.",
    benefits5: "Satisfying and easy to carry.",
  }
];
export const testimonialsData = [
  {
    image: "/testimonial1.jpg",
    name: "John Doe",
    desc: "John is an experienced food blogger who has traveled across continents to discover unique flavors and culinary traditions. His blog captures not just the essence of food but also the stories of the people behind it. From street food vendors in Asia to fine dining restaurants in Europe, John shares his experiences with vibrant storytelling and mouthwatering photography. His passion for food is evident in every post, making him a trusted voice in the world of gastronomy.",
    profession: "Food Blogger",
  },
  {
    image: "/testimonial2.jpg",
    name: "Jane Smith",
    desc: "Jane is a renowned chef with over a decade of experience working in top-rated kitchens. She specializes in blending traditional recipes with modern techniques to create dishes that are as visually stunning as they are delicious. Jane's journey began in her grandmother's kitchen, where she learned the importance of fresh ingredients and attention to detail. Today, she inspires others to explore their culinary potential through her recipes, cooking classes, and guest appearances on food shows.",
    profession: "Chef",
  },
  {
    image: "/testimonial5.jpg",
    name: "Robert Brown",
    desc: "Robert is a highly respected restaurant critic whose insightful reviews have guided food lovers to some of the finest dining experiences. With a palate as sharp as his pen, Robert combines a deep understanding of cuisine with an appreciation for ambiance and service. His critiques are known for their honesty and depth, often highlighting hidden gems that might otherwise go unnoticed. Whether reviewing a Michelin-starred restaurant or a cozy neighborhood café, Robert's words carry weight in the culinary world.",
    profession: "Restaurant Critic",
  },
  {
    image: "/testimonial3.jpg",
    name: "Emily White",
    desc: "Emily is a talented pastry chef whose creations are nothing short of edible art. Her desserts are a perfect blend of flavor and aesthetics, showcasing her mastery of techniques like sugar sculpting and chocolate tempering. Emily draws inspiration from her travels, infusing her confections with global influences. From delicate French pastries to bold, experimental desserts, she takes pride in crafting sweets that not only satisfy the taste buds but also evoke joy and wonder.",
    profession: "Pastry Chef",
  },
  {
    image: "/testimonial6.jpg",
    name: "Michael Green",
    desc: "Michael is a passionate food enthusiast who loves exploring diverse cuisines and sharing his culinary adventures with others. Whether trying out exotic dishes in a foreign country or experimenting with recipes in his kitchen, Michael approaches food with curiosity and enthusiasm. His social media platforms are filled with vibrant photos, detailed reviews, and tips for fellow food lovers. Michael's motto is simple: 'Good food brings people together,' and he lives by it every day.",
    profession: "Food Enthusiast",
  },
  {
    image: "/testimonial3.jpg",
    name: "Sarah Johnson",
    desc: "Sarah is a lifestyle blogger who seamlessly combines her love for food, travel, and wellness into a captivating online presence. Her blog features everything from healthy recipes and meal prep ideas to travel diaries and self-care tips. Sarah's authentic voice and relatable content resonate with her audience, inspiring them to lead balanced and fulfilling lives. She believes that a good meal is at the heart of every great memory and shares that philosophy through her writing.",
    profession: "Lifestyle Blogger",
  },
];
export const popularCardsData = [
  {
    id: "1",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "2",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "3",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "4",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "5",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "6",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "7",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "8",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "9",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: "10",
    category: "fries",
    name: "Classic French Fries",
    image: "/fries1.jpg",
    des: "Golden and crispy, our classic fries are a timeless favorite.",
    price: 20,
    discount: "$30",
    stock: "In Stock",
    reviews: 22,
    des1: "Nam tristique porta ligula, vel viverra sem eleifend nec. Nulla sed purus augue, eu euismod tellus. Nam mattis eros nec mi sagittis sagittis. Vestibulum suscipit cursus bibendum. Integer at justo eget sem auctor auctor eget vitae arcu. Nam tempor malesuada porttitor. Nulla quis dignissim ipsum. Aliquam pulvinar iaculis justo, sit amet interdum sem hendrerit vitae. Vivamus vel erat tortor. Nulla facilisi. In nulla quam, lacinia eu aliquam ac, aliquam in nisl.",
    des2: "Suspendisse cursus sodales placerat. Morbi eu lacinia ex. Curabitur blandit justo urna, id porttitor est dignissim nec. Pellentesque scelerisque hendrerit posuere. Sed at dolor quis nisi rutrum accumsan et sagittis massa. Aliquam aliquam accumsan lectus quis auctor. Curabitur rutrum massa at volutpat placerat. Duis sagittis vehicula fermentum. Integer eu vulputate justo. Aenean pretium odio vel tempor sodales. Suspendisse eu fringilla leo, non aliquet sem.",
    benefits1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    benefits5: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];
